const SET_INGREDIENT_DETAILS = 'SET_INGREDIENT_DETAILS';
const REMOVE_INGREDIENT_DETAILS = 'REMOVE_INGREDIENT_DETAILS';
const SHOW_DETAILS = 'SHOW_DETAILS';
const HIDE_DETAILS = 'HIDE_DETAILS';

export { SET_INGREDIENT_DETAILS, REMOVE_INGREDIENT_DETAILS, SHOW_DETAILS, HIDE_DETAILS };