export const testIngredients = [
  {
    "_id": "643d69a5c3f7b9001cfa093c",
    "name": "Краторная булка N-200i",
    "type": "bun",
    "proteins": 80,
    "fat": 24,
    "carbohydrates": 53,
    "calories": 420,
    "price": 1255,
    "image": "https://code.s3.yandex.net/react/code/bun-02.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
    "__v": 0
  },
  {
    "_id": "643d69a5c3f7b9001cfa0942",
    "name": "Соус Spicy-X",
    "type": "sauce",
    "proteins": 30,
    "fat": 20,
    "carbohydrates": 40,
    "calories": 30,
    "price": 90,
    "image": "https://code.s3.yandex.net/react/code/sauce-02.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/sauce-02-large.png",
    "__v": 0
  },
  {
    "_id": "643d69a5c3f7b9001cfa0940",
    "name": "Говяжий метеорит (отбивная)",
    "type": "main",
    "proteins": 800,
    "fat": 800,
    "carbohydrates": 300,
    "calories": 2674,
    "price": 3000,
    "image": "https://code.s3.yandex.net/react/code/meat-04.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/meat-04-large.png",
    "__v": 0
  },
  {
    "_id": "643d69a5c3f7b9001cfa0946",
    "name": "Хрустящие минеральные кольца",
    "type": "main",
    "proteins": 808,
    "fat": 689,
    "carbohydrates": 609,
    "calories": 986,
    "price": 300,
    "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
    "__v": 0
  },
  {
    "_id": "643d69a5c3f7b9001cfa094a",
    "name": "Сыр с астероидной плесенью",
    "type": "main",
    "proteins": 84,
    "fat": 48,
    "carbohydrates": 420,
    "calories": 3377,
    "price": 4142,
    "image": "https://code.s3.yandex.net/react/code/cheese.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/cheese-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/cheese-large.png",
    "__v": 0
  },
  {
    "_id": "643d69a5c3f7b9001cfa0946",
    "name": "Хрустящие минеральные кольца",
    "type": "main",
    "proteins": 808,
    "fat": 689,
    "carbohydrates": 609,
    "calories": 986,
    "price": 300,
    "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
    "__v": 0
  },
  {
    "_id": "643d69a5c3f7b9001cfa0946",
    "name": "Хрустящие минеральные кольца",
    "type": "main",
    "proteins": 808,
    "fat": 689,
    "carbohydrates": 609,
    "calories": 986,
    "price": 300,
    "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
    "__v": 0
  },
  {
    "_id": "643d69a5c3f7b9001cfa0944",
    "name": "Соус традиционный галактический",
    "type": "sauce",
    "proteins": 42,
    "fat": 24,
    "carbohydrates": 42,
    "calories": 99,
    "price": 15,
    "image": "https://code.s3.yandex.net/react/code/sauce-03.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/sauce-03-large.png",
    "__v": 0
  }
];

export const testFeed = [
  testIngredients,
  testIngredients,
  testIngredients,
  testIngredients,
  testIngredients,
  testIngredients,
  testIngredients,
  testIngredients,
  testIngredients,
  testIngredients
];

export const testOrderList = [
  "977334",
  "612650",
  "749339",
  "796026",
  "289627",
  "744075",
  "962477",
  "944687",
  "872973",
  "343018",
  "977240",
  "958593",
  "884023",
  "558574"
];